spring.application.name=jobfinder
management.endpoints.web.exposure.include=health,info,prometheus

usajobs.api.key=YOUR-API-KEY
usajobs.api.url=https://data.usajobs.gov/api
usajobs.user.agent=YOUR-EMAIL-GOES HERE
